[package]
distribution = "2201.3.2"
org = "ballerinax"
name = "azure.storage"
version = "4.2.0"
authors = ["Ballerina"]
export = ["azure.storage", "azure.storage.files", "azure.storage.blobs"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-storage-service"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
